/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Blue.h"
#include "Blue_aliases.h"
#include "Green.h"
#include "Green_aliases.h"
#include "Pwm.h"
#include "Pwm_Clk.h"
#include "Uart_Clk.h"
#include "Rx_Int.h"
#include "Uart.h"
#include "Uart_SPI_UART.h"
#include "Uart_PINS.h"
#include "Uart_SPI_UART_PVT.h"
#include "Uart_PVT.h"
#include "Uart_BOOT.h"
#include "Uart_tx.h"
#include "Uart_tx_aliases.h"
#include "Uart_rx.h"
#include "Uart_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

